// Generated by scripts/brand/build-logo.mjs from brand/logo/. Do not edit: change the sources and run
// `npm run brand:build`.

/** The MusiLynk mark ("A4 One-line M") on the 100x100 grid, cropped to its ink box. */
export const BRAND_MARK_VIEWBOX = '13 16 74 68';
/** Width / height of the mark. */
export const BRAND_MARK_ASPECT = 1.0882;
/** Filled path data of the mark (draw with the evenodd fill rule if BRAND_MARK_EVENODD). */
export const BRAND_MARK_PATHS = [
  'm25.4 16 36.3 39.2q3.6 3.5 4.7 8.5 1.1 5-.8 9.8-1.9 4.7-6.2 7.6-4.3 2.9-9.4 2.9-5.1 0-9.4-2.9-4.2-2.9-6.2-7.6-1.9-4.8-.8-9.8 1.1-5 4.7-8.5l2.1-2.1 7.6 7.2-2.2 2.3-.1.1q-3.1 2.9-1.5 6.9 1.6 3.9 5.8 3.9 4.2 0 5.8-3.9 1.6-4-1.5-6.9l3.6-3.8-3.8 3.6-30.6-33.1v54.6h-10.5v-68zm25.6 25.5 23.6-25.5h12.4v68h-10.5v-54.6l-17.9 19.4z',
];
export const BRAND_MARK_EVENODD = false;

/** Mark colour on dark and on light backgrounds (brand/logo/logo.config.json). */
export const BRAND_MARK_ON_DARK = '#A99BFF';
export const BRAND_MARK_ON_LIGHT = '#5B3CF0';
/** App-icon tile: gradient and flat fallback. */
export const BRAND_TILE_FROM = '#6C4DFF';
export const BRAND_TILE_TO = '#4A2BD6';
export const BRAND_TILE_FLAT = '#5B3CF0';

/** The app-icon tile as a standalone SVG document (public/musilynk-mark.svg), for image renderers. */
export const BRAND_TILE_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" aria-label="MusiLynk"><title>MusiLynk</title><defs><linearGradient id="mlk-tile" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#6C4DFF"/><stop offset="1" stop-color="#4A2BD6"/></linearGradient></defs><rect width="100" height="100" rx="22.5" fill="url(#mlk-tile)"/><g transform="translate(22 24.27) scale(0.757) translate(-13 -16)"><path fill="#FFFFFF" d="M25.4,16L61.67,55.23Q65.28,58.73 66.36,63.66Q67.46,68.68 65.56,73.46Q63.65,78.23 59.4,81.12Q55.14,84 50,84Q44.86,84 40.6,81.12Q36.35,78.23 34.44,73.46Q32.54,68.68 33.64,63.66Q34.72,58.73 38.33,55.23L40.35,53.05L47.96,60.28L45.82,62.6L45.7,62.72Q42.63,65.63 44.2,69.57Q45.76,73.5 50,73.5Q54.24,73.5 55.8,69.57Q57.37,65.63 54.3,62.72L57.92,58.91L54.06,62.47L23.5,29.41L23.5,84L13,84L13,16ZM51.01,41.52L74.6,16L87,16L87,84L76.5,84L76.5,29.41L58.62,48.75Z"/></g></svg>';
