/**
 * Editorial photos live in /img as `<name>-<width>.avif` and `<name>-<width>.webp`, generated by
 * scripts/perf/build-photos.mjs. These helpers build the srcset for one and pick the intrinsic size
 * to declare so the layout never shifts.
 */

export type PhotoFormat = 'avif' | 'webp';

/** Widths every editorial photo ships: 480 for a phone tile, 800 for a 2x tile or a phone header, 1600 for desktop. */
export const PHOTO_WIDTHS = [480, 800, 1600] as const;
/** The landing hero: a veena player mid-concert. Also the one photo that ships HERO_PHOTO_WIDTHS. */
export const HERO_PHOTO = 'veena-concert';
/** The home hero (the LCP image) ships finer steps so a phone at 2 to 3x density never downloads the 1600. */
export const HERO_PHOTO_WIDTHS = [480, 768, 1200, 1600] as const;

const ALL_WIDTHS: readonly number[] = [...new Set<number>([...PHOTO_WIDTHS, ...HERO_PHOTO_WIDTHS])];
const LARGEST = PHOTO_WIDTHS[PHOTO_WIDTHS.length - 1];

/** `/img/hero-tabla` -> `/img/hero-tabla-480.webp 480w, /img/hero-tabla-800.webp 800w, ...`. */
export function photoSrcSet(
  base: string,
  widths: readonly number[] = PHOTO_WIDTHS,
  format: PhotoFormat = 'webp',
): string {
  return widths.map((w) => `${photoUrl(base, w, format)} ${w}w`).join(', ');
}

/** The file for one width; unknown widths fall back to the largest. */
export function photoUrl(base: string, width: number = LARGEST, format: PhotoFormat = 'webp'): string {
  const w = ALL_WIDTHS.includes(width) ? width : LARGEST;
  return `${base.replace(/\.(webp|avif)$/, '').replace(/-(480|640|768|800|960|1200|1280|1600)$/, '')}-${w}.${format}`;
}

/** Largest centred square in a w x h image: where to start reading and how long each side is. */
export function squareCropRect(width: number, height: number) {
  const side = Math.max(1, Math.min(width, height));
  return { sx: Math.floor((width - side) / 2), sy: Math.floor((height - side) / 2), side };
}

/** Edge length in pixels of an uploaded profile or act photo. */
export const PROFILE_PHOTO_PX = 512;
